# Generated by Django 3.2 on 2025-04-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20250414_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='achivements',
            new_name='achievements',
        ),
    ]
